---
dist: focal
language: python
python: "3.10"
os: linux
services:
  - docker
install:
  - pip install -I pipenv
env:
  jobs:
    - MOLECULE_DISTRO=debian:bullseye-slim
    - MOLECULE_DISTRO=debian:buster-slim
script:
  - ./test.sh
