---
dist: focal
language: python
python: "3.9"
os: linux
services:
  - docker
install:
  - pip install pipenv
env:
  jobs:
    - MOLECULE_DISTRO=debian:bullseye-slim
    - MOLECULE_DISTRO=debian:buster-slim
script:
  - ./test.sh
notifications:
  email:
    recipients:
      - desarrollo.benders@idealista.com
      if: branch = master
      on_success: change
      on_failure: always
