---
dist: xenial
language: python
python: "3.7"
os: linux
services:
  - docker
install:
  - pip3 install cookiecutter
env:
  jobs:
    - MOLECULE_DISTRO=debian:jessie-slim
    - MOLECULE_DISTRO=debian:stretch-slim
    - MOLECULE_DISTRO=debian:buster-slim
    
script:
  - ./test.sh