---

- name: {{ cookiecutter.app_name | upper }} | Install
  import_tasks: install.yml
  tags:
    - {{ cookiecutter.app_name }}_install

- name: {{ cookiecutter.app_name | upper }} | Configure
  import_tasks: config.yml
  tags:
    - {{ cookiecutter.app_name }}_configure
{% if cookiecutter.has_service  == 'True' %}
- name: {{ cookiecutter.app_name | upper }} | Service
  import_tasks: service.yml
  tags:
    - {{ cookiecutter.app_name }}_service
{% endif %}